---
- name: Ensure libvirt and related packages installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - libvirt
    - libvirt-client  # virt-host-validate
    - libvirt-python
    - libvirt-daemon-kvm
    - qemu-kvm

# vim:sw=2:ts=2:et:
