---
yum_repos:
  - id: rhel-7.3-server-rpms
    type: iso
    src: /var/lib/libvirt/images/rhel-server-7.3-x86_64-dvd.iso
    dest: /var/lib/libvirt/images/rhel-server-7.3-x86_64-dvd.iso
    datadir: /var/www/html/pub/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

  - id: nux-misc
    type: reposync

  - id: custom-rpms
    type: createrepo
    src: files/*.rpm

# vim:sw=2:ts=2:et:
