---
# *** WORKING IN PROGRESS ***

# .. note::
#    virt is still in preview state so that I implement this by myself.
#    :seealso: http://docs.ansible.com/ansible/virt_module.html
#
- name: Check if the guest exists
  command: "virsh dominfo {{ _guest.name }}"
  ignore_errors: true
  register: find_libvirt_guest

- name: Create working dir to save scripts for guest
  file:
    path: "/tmp/{{ _guest.name }}_build"
    state: directory
    mode: 0700

- name: Create install script for guest
  template:
    src: "{{ _guest.install_script }}.j2"
    dest: "/tmp/{{ _guest.name }}_build/{{ _guest.install_script }}"
  when:
    - "{{ _guest.create is defined and _guest.create }}"
    - "{{ _guest.install_script is defined and _guest.install_script }}"

- name: Create build script for guest
  template:
    src: vmbuild.sh.j2
    dest: "/tmp/{{ _guest.name }}_build/vmbuild.sh"
  when:
    - "{{ _guest.create is defined and _guest.create }}"
    - "{{ _guest.install_script is defined and _guest.install_script }}"

- name: Check if install iso exists for guest
  file:
    path: "{{ _guest.install_iso }}"
    state: file
  when:
    - "{{ _guest.create is defined and _guest.create }}"
    - "{{ _guest.install_script is defined and _guest.install_script }}"
    - "{{ _guest.install_iso is defined and _guest.install_iso }}"

- name: Create and install guest
  shell: "bash -x /tmp/{{ _guest.name }}_build/vmbuild.sh"
  when:
    - "{{ _guest.create is defined and _guest.create }}"
    - "{{ _guest.install_script is defined and _guest.install_script }}"

# vim:sw=2:ts=2:et:
