---
- name: Ensure libvirt and related packages installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - NetworkManager
    - libvirt
    - libvirt-python
    - libvirt-daemon-kvm
    - python-lxml  # Required for 'virt_net' module.
    - qemu-kvm
  tags:
    - kvm

# vim:sw=2:ts=2:et:
