---
- name: Setup yum repo file for this repo
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
  with_items:
    - template: yum.repo.j2
      dest: "/etc/yum.repos.d/{{ _repo.id }}.repo"

# vim:sw=2:ts=2:et:
