---
- name: Ensure dedicated git group exists
  group:
    name: "{{ git.group|default('git') }}"

- name: Ensure dedicated git user exists
  user:
    name: "{{ git.user|default('git') }}"
    group: "{{ git.group|default('git') }}"
    generate_ssh_key: yes
    shell: /usr/bin/git-shell

- name: Ensure git repos root dir exists
  file:
    path: "{{ git.root }}"
    state: directory
    mode: "0775"
    owner: "{{ git.user|default('git') }}"
    group: "{{ git.group|default('git') }}"
    setype: git_content_t

- name: Ensure git bare repos initialized
  shell: "test -d {{ item.dest }} || git init --bare --shared {{ item.dest }}"
  with_items: "{{ git.repos|rejectattr('repo')|list }}"

- name: Ensure git remote repos initialized
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes
  with_items: "{{ git.repos|selectattr('repo')|list }}"

- name: Ensure git repos exported
  file:
    path: "{{ item.dest }}/git-daemon-export-ok"
    mode: "0644"
    owner: "{{ git.user|default('git') }}"
    group: "{{ git.group|default('git') }}"
    state: touch
  with_items: "{{ git.repos|selectattr('dest')|list }}"

- name:
  lineinfile:
    dest: /etc/gitweb.conf
    line: "our $projectroot = '{{ git.root }}';"

- name: Ensure httpd is running
  service:
    name: httpd
    state: running

# vim:sw=2:ts=2:et:
