---
- name: Enable Activation Keys
  shell: |
    aks=$(hammer --output=yaml activation-key list \
      --organization-id `cat ~/.hammer/orgid.txt` | sed -nr 's/.*Name: (.)$/,\1,/p')
    {% for key in satellite.activation_keys if key.name -%}
    echo "${aks}" | grep -qE '^{{ key.name }}$' 2>/dev/null || \
    hammer activation-key create --organization-id `cat ~/.hammer/orgid.txt` \
      --name '{{ key.name }}' \
      {{ '--description "%s"' % key.description if key.description }} \
      --content-view '{{ key.cv or "Default Organization View" }}' \
      --lifecycle-environment '{{ key.env or "Library" }}' \
      {{ '--max-content-hosts %s' % key.max if key.max  }} \
    {% if key.host_collection %}&& \
    hammer activation-key add-host-collection --organization-id `cat ~/.hammer/orgid.txt` \
      --name '{{ key.name }}' --host-collection '{{ key.host_collection }}'{% endif %}
    {% endfor %}
  changed_when: false
  when:
    - satellite.activation_keys is defined
    - satellite.activation_keys
    - satellite.activation_keys is sequence

# vim:sw=2:ts=2:et:
