---
# @see https://fedoraproject.org/wiki/How_to_enable_nested_virtualization_in_KVM

- name: Check if Nested KVM is supported and enabled
  shell: "test $(cat /sys/module/kvm_*/parameters/nested) = '1'"
  ignore_errors: true
  register: check_if_nested_kvm_is_enabled

- name: Enable Nested KVM support statically
  template:
    src: nested_kvm.conf.j2
    dest: /etc/modprobe.d/nested_kvm.conf
    backup: true
  when: check_if_nested_kvm_is_enabled|failed

# Depends on the above:
- name: Enable Nested KVM for Intel CPUs support dynamically 
  shell: "rmmod kvm-intel && modprobe kvm-intel"
  when:
    - "Intel" in ansible_processor[0]
    - check_if_nested_kvm_is_enabled|failed

- name: Enable Nested KVM for AMD CPUs support dynamically 
  shell: "rmmod kvm-amd && modprobe kvm-amd"
  when:
    - "AMD" in ansible_processor[0]
    - check_if_nested_kvm_is_enabled|failed

# vim:sw=2:ts=2:et:
