---
yum_repo_server:
# yum_repo_server: ansible.example.com

httpd:
  packages:
    # httpd or nginx
    - httpd
    - yum-utils

  # httpd or nginx
  service: httpd
  www_root: /var/www/html
  repos_subdir: pub

yum_repos:
#  # id: Repo's ID, type: iso (image) or reposync, src: Local iso image path
#  # (type=iso only), iso_path: Remote iso image path (type=iso only)
#
#  - id: rhel-7.3-server-rpms
#    type: iso
#    src: /var/lib/libvirt/images/rhel-server-7.3-x86_64-dvd.iso
#    iso_path: /var/lib/libvirt/images/rhel-server-7.3-x86_64-dvd.iso
#    gpgkey: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
#
#  - id: rhel-7-server-rpms
#    type: reposync
#    gpgkey: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
#
#  - id: rhel-7-server-extras-rpms
#    type: reposync
#    gpgkey: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

# vim:sw=2:ts=2:et:
