---
# This playbook will run before installation.

- name: Ensure libvirt and related packages installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - NetworkManager
    - libvirt
    - libvirt-python
    - python-lxml  # Required for 'virt_net' module.
    - qemu-kvm
  tags:
    - kvm

- name: Check if KVM device is ready
  stat:
    path: /dev/kvm
  register: kvm_device
  ignore_errors: true
  tags:
    - kvm

- name: Reboot the host to enable KVM support as needed
  shell: "sleep 3 && reboot"
  async: 1
  poll: 0
  when: kvm_device.stat.ischr is not defined or kvm_device.stat.ischr == False
  tags:
    - kvm

# :seealso: http://docs.ansible.com/ansible/wait_for_module.html
- name: Wait for the host reboots
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" delay=10
  become: False
  when: kvm_device.stat.ischr is not defined or kvm_device.stat.ischr == False

# vim:sw=2:ts=2:et:
