---
- name: Ensure libvirt and related packages installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - NetworkManager
    - libvirt
    - libvirt-python
    - python-lxml  # Required for 'virt_net' module.
    - qemu-kvm
  tags:
    - kvm

- name: Check if KVM device is ready
  stat:
    path: /dev/kvm
  ignore_errors: true
  register: kvm_device
  tags:
    - kvm

# vim:sw=2:ts=2:et:
