---
# This playbook will run before installation.

- name: Check if libvirtd is running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - libvirtd
    - NetworkManager

- name: Check if libvirt lab network is ready
  command: "virsh net-info {{ libvirt_lab_network_name }}"
  register: find_libvirt_lab_networks
  ignore_errors: true

- name: Install libvirt netowrk XML file
  template:
    src: libvirt-lab-network.xml.j2
    dest: /etc/libvirt/qemu/networks/lab.xml
    backup: yes
  when: find_libvirt_lab_networks|failed

# Alternative (it should require some more checks of the content of the file):
#
#- name: Update libvirt default network
#  command: "{{ items }}"
#  with_items:
#    - virsh net-update domain add
#  when: ...

- name: Create libvirt netwroks
  command: "virsh net-define /etc/libvirt/qemu/networks/{{ item }}.xml"
  with_items:
    - "{{ libvirt_lab_network_name }}"
  when: find_libvirt_lab_networks|failed

- name: Start libvirt netwroks
  shell: "virsh net-start {{ item }} && virsh net-autostart {{ item }}"
  with_items:
    - "{{ libvirt_lab_network_name }}"
  when: find_libvirt_lab_networks|failed

# @see https://goo.gl/UjGtfw
- name: Configure local DNS for NetworkManager
  template:
    src: localdns.conf.j2
    dest: /etc/NetworkManager/conf.d/localdns.conf
    backup: yes

- name: Configure DNS resolv for NetworkManager
  template:
    src: libvirt_dnsmasq.conf.j2
    dest: /etc/NetworkManager/dnsmasq.d/libvirt_dnsmasq.conf
    backup: yes
  notify: "Restart NetworkManager"

# vim:sw=2:ts=2:et:
