---
libvirt_networks:
  - name: default
    create: false
    state: started

  - name: &net_1_name lab
    create: true
    state: started
    autostart: true

    bridge: virbr10
    domain: example.com
    gw_ip: 192.168.125.1
    gw_hostname: ansible
    range_start: 192.168.125.128
    range_end: 192.168.125.254
    hosts:
      - ip: &guest_1_ip 192.168.125.101
        hostname: &guest_1_hostname web01
        mac: &guest_1_mac "52:54:00:12:51:01"
      - ip: &guest_2_ip 192.168.125.102
        hostname: &guest_2_hostname web02
        mac: &guest_2_mac "52:54:00:12:51:02"

libvirt_guests:

  - name: web01
    description: Web server 01
    create: true

    auto_install_script:
     src: rhel-7-web-ks.cfg.j2
     dest: ks.cfg

    hostname: web01.example.com

    virtinst_disks:
      # choices, bus: scsi (virtio-scsi), virtio, ..., size: int [GB]
      - bus: scsi
        size: 20

     # @see libvirt_networks (libvirt-host role)
    virtinst_net_interfaces:
      - network: lab
        model: virtio
        mac: "52:54:00:12:51:01"

    virtinst_wait: 20
    virtinst_ram: 1024
    virtinst_cpu: host
    virtinst_vcpus: 1
    virtinst_os_type: linux
    virtinst_os_variant: rhel7
    virtinst_location: /var/lib/libvirt/images/rhel-server-7.3-x86_64-dvd.iso
    virtinst_options:
      - "--controller=scsi,model=virtio-scsi"
      - "--initrd-inject=ks.cfg"
      - "--extra-args='inst.loglevel=debug inst.text inst.ks=file:/ks.cfg net.ifnames=0'"

# vim:sw=2:ts=2:et:
