---
- debug: var=_repo
- assert:
    that:
      - _repo.id is defined
      - _repo.id
    msg: "<repo> in 'yum_repos' must have non empty 'id' parameter"

- set_fact:
    repo_dir: "{{ httpd.www_root }}/{{ httpd.repos_subdir }}/{{ _repo.id }}"

- include: _setup_repo_with_iso_images.yml
  when:
    - _repo.iso_path is defined
    - _repo.iso_path

- include: _setup_repo_by_reposync.yml
  when:
    - _repo.type is defined
    - _repo.type == 'reposync'

- include: _setup_repo_by_createrepo.yml
  when:
    - _repo.type is defined
    - _repo.type == 'createrepo'
    - _repo.rpms is defined
    - _repo.rpms
    - _repo.rpms|sequence

- include: _create_yum_repo_file.yml

# vim:sw=2:ts=2:et:
