---
- name: Ensure the iso image to provide the contents of the yum repo exists
  copy:
    src: "{{ _repo.src }}"
    dest: "{{ _repo.iso_path }}"
    force: false

- name: Ensure the iso image is mounted automatically
  mount:
    fstype: iso9660
    opts: ro,loop
    # ansible < 2.3
    name: "{{ httpd.www_root }}/{{ httpd.repos_subdir }}/{{ _repo.id }}"
    # ansible >= 2.3
    # path: "{{ httpd.www_root }}/{{ httpd.repos_subdir }}/{{ _repo.id }}"
    src: "{{ _repo.iso_path }}"
    state: mounted

# Alternative of the above task if 'preview' modules are excluded from use.
#
# - name: Ensure repo's dir exists for the repo
#   file:
#     path: "{{ httpd.www_root }}/{{ httpd.repos_subdir }}/{{ _repo.id }}"
#     state: directory
#     # mode: 0755  # It looks failed if it's already exists and mounted isos under it.
#
# - name: Setup mount for the iso image for the repo
#   lineinfile:
#     dest: /etc/fstab
#     state: present
#     regexp: "^{{ _repo.iso_path }}"
#     line: "{{ _repo.iso_path }} {{ httpd.www_root }}/{{ httpd.repos_subdir }}/{{ _repo.id }} iso9660 ro,loop 0 0"
#
# - name: Mount the iso image for the repo
#   shell: "mount | grep -q {{ _repo.iso_path }} || mount {{ _repo.iso_path }}"

# vim:sw=2:ts=2:et:
