---
- name: Ensure httpd servcie is running
  service:
    name: "{{ httpd.service|default('httpd') }}"
    state: started

- include: _setup_repo.yml
  with_items: "{{ yum_repos }}"
  loop_control:
    loop_var: _repo

# vim:sw=2:ts=2:et:
